apiVersion: v1
kind: Namespace
metadata:
  name: mysql-ns
  labels:
    name: mysql-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-ns
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4=
  MYSQL_DATABASE: bGVhcm5pbmc=
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
    - name: mysql-container
      image: mysql:8.0

      ports:
        - containerPort: 3306

      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"

      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE