worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            return 200 "hello world from nginx!";
        }

        location /l {
            return 200 "listening on port 80";
        }
    }
}