apiVersion: v1
kind: Namespace
metadata:
  name: backend-ns
  labels:
    name: backend-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-budget
  namespace: backend-ns
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
    pods: "3"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-backend-ns-deployment
  namespace: backend-ns
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-sit
  template:
    metadata:
      labels:
        app: nginx-sit
    spec:
      containers:
        - name: nginx-container
          image: dheeraj1429/k8s-namespace-learning:0.3
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sit-service
  namespace: backend-ns
spec:
  selector: 
    app: nginx-sit
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer