apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dev-deployment
  namespace: dev
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nginx-sit
  template:
    metadata:
      labels:
        app: nginx-sit
    spec:
      containers:
        - name: nginx-container
          image: dheeraj1429/k8s-namespace-learning:0.3
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sit-service
  namespace: dev
spec:
  selector: 
    app: nginx-sit
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer