# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: fluent-bit-deployment

# spec:
#   replicas: 1

#   selector:
#     matchLabels:
#       app: fluent-bit

#   template:
#     metadata:
#       labels:
#         app: fluent-bit
#     spec:
#       containers:
#         - name: fluent-bit-container
#           image: dheeraj1429/nginx-logs-fluent-bit-learning-image:0.1
#           ports:
#             - containerPort: 2020
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: fluent-bit-service

# spec:
#   selector:
#     app: fluent-bit
#   ports:
#   - name: fluent-bit-service
#     port: 2020
#     protocol: TCP
#   type: LoadBalancer