worker_processes auto;

events {
    worker_connections 1024;
}

http {

    server {

        listen 80;
        server_name localhost;

        root /var/www/fallback;

        location / {
            return 200 "Hello from the fallback nginx server!";
        }
    }
}
