apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: {{ .Values.namespace }}
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: mysql-container
      image: "{{ .Values.pod.imageName }}:{{ .Values.pod.tag }}"
      ports:
        - containerPort: {{ .Values.pod.containerPort }}
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mysql-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mysql-secret
      resources:
        requests:
          memory: 1Gi
          cpu: "1"
        limits:
          memory: 2Gi
          cpu: "1"
      volumeMounts:
        - name: storage
          mountPath: {{ .Values.pod.volumeMounts.mountPath }}