apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: {{ .Values.namespace }}
spec:
  hard:
    requests.cpu: '1'
    limits.cpu: '1'
    requests.memory: 1Gi
    limits.memory: 2Gi