version: "3.8"

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: unless-stopped
    ports:
      - 5341:80
    volumes:
      - seq_data:/data
    environment:
      - ACCEPT_EULA=y
      - SEQ_PASSWORD=seq_password

  fluent_bit:
    image: cr.fluentbit.io/fluent/fluent-bit:latest
    container_name: fluent_bit
    ports:
      - 2020:2020
      - 8000:8000
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml:ro
    command: -c /fluent-bit/etc/fluent-bit.yaml
    environment:
      - SEQ_HOST=seq
      - SEQ_PORT=80
      - SEQ_API_KEY=seq_password
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      seq:
        condition: service_started

volumes:
  seq_data: