worker_processes auto;

events {
	worker_connections 1024;
}

http {
	keepalive_timeout 60;

	#include /etc/nginx/mime.types;

	client_body_timeout 60s;
	client_header_buffer_size 1k;
	client_header_timeout 60s;

	limit_req_zone $binary_remote_addr zone=one:10m rate=30r/m;
	limit_conn_zone $binary_remote_addr zone=addr:10m;

	#log_format custom '$remote_addr - $remote_user [$time_local] r=$request s=$status bd=$body_bytes_sent ra=$http_user_agent rt=$request_time';
	#access_log /var/log/nginx/access-logs.log custom;
	#error_log /var/log/nginx/error-logs.log warn;

	gzip on;
	gzip_comp_level 5;
	gzip_min_length 256;
	gzip_proxied any;
	gzip_types
		text/plain
		application/json;

	server {
		listen 80 default_server;
		root /var/www/cafe;
		
		server_name _;
		# server_name easy.com;
		# return 444;

		index index.html index.htm;
		
		allow 192.168.1.0/24;
		deny all;

		limit_conn addr 10;
		limit_conn_status 429;
		limit_conn_log_level warn;

		location =/ {
			return 200 "Hello from nginx!";
		}

		location /error {
			limit_except POST { deny all; }
			return 200 "Hello from the error route!"; 
		}

		location /assets/images {
			alias /var/www/cafe/images;
			
			expires 30d;
			add_header Cache-Control "public";
			try_files $uri $uri/ = 404;	
		}

		location /assets {
			expires 1y;
			add_header Cache-Control "public";
			alias /var/www/cafe;
			try_files $uri $uri/ =404;
		}

		location /basic-auth {
			if ($http_authorization != "Bearer my-secret-abc-123") {
				return 401 "Unauthorized: Invalid or missing token";
			}			

			return 200 "Restricted respose!";
		}

		# The primary difference lies in data format and memory efficiency. $remote_addr holds the client’s IP address as a variable string, 
		# which can vary in size from 7 to 15 bytes depending on the IP version.  In contrast, $binary_remote_addr stores the IP address 
		# in a binary representation, which is fixed at 4 bytes for IPv4 and 16 bytes for IPv6.

		location /api {
			limit_except GET { deny all; }

			limit_rate 100k;
			limit_req zone=one burst=20 delay=8;
			
			return 200 "Hello from the nginx here is you uri: $uri, args: $args, bytes sent: $bytes_sent,
			connection: $connection, connection request made the single connection $connection_requests, content type: $content_type
			Document root: $document_root, host: $host, host name: $hostname, isHttpsOn: $https, proxy procol address: $proxy_protocol_addr,
			request: $request, request body: $request_body, content type: $http_content_type, method: $request_method,
			binary_remote_addr $binary_remote_addr, remote_addr: $remote_addr, remote_user: $remote_user, request: $request, status: $status,
			http_referer: $http_referer, http_user_agent: $http_user_agent, time_local: $time_local, request_time: $request_time, 
			upstream_connect_time: $upstream_connect_time, upstream_response_time $upstream_response_time, http_authorization: $http_authorization, gzip_ratio: $gzip_ratio
			";
		}

		location /website {
			alias /var/www/personal-blog-website;
			index index.html index.html 404;
		}

		

		# location /pass/ {
		#	proxy_pass http://fallback-server:8080;
		#	proxy_set_header Host $host;
		#	proxy_set_header X-Real-IP $remote_addr;
		#}
		
	}
}
