version: "3.8"

services:
  server:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - 80:80
    volumes:
      # - ./basic.html:/usr/share/nginx/html/index.html:ro
      # - ./basic.html:/usr/share/nginx/html/about/index.html:ro
      # - ./basic.html:/usr/share/nginx/html/about/basic.html:ro
      - ./image.png:/var/www/cafe/image.png
      - ./cafe.coder.com.conf:/etc/nginx/nginx.conf:ro
      - ./personal-blog-website:/var/www/personal-blog-website
      - ./images:/var/www/cafe/images
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #fallback-server:
  #  image: nginx:latest
  #  container_name: nginx-fallback-server
  #  ports:
  #    - 8080:80
  #  volumes:
  #    - ./fallback.coder.com.conf:/etc/nginx/nginx.conf:ro
